
### Lidar use cases at the Northwest German Forest Research Institute


#### Forest Growth
*(Ertragskunde / Waldverjüngung/ Wachstums- und Risikomodellierung / Waldinventur, Informatik und Biometrie)*

- Tree growth
- Forest stand structure
- Species distribution / stand mixture
- Mortality
- Risk modelling 
- Inventory upscaling


#### Forest Protection
*(Käfer und Mittelprüfung / Schmetterlinge und Mäuse / Mykologie und Komplexerkrankungen / Fernerkundung und GIS)*

- Forest Disturbance Detection
- Planning of pesticide application


#### Forest Genetic Resources
*(Züchtung und Prüfung forstlichen Vermehrungsgutes)*

- experimental area assessment (growth)


#### Environmental Control 
*(Intensives Umweltmonitoring / Wald- und Bodenzustand / Nährstoffmanagement / Umweltanalytik)*

- LAI estimation
- hydrological modelling
- forest condition monitoring
- forest stand characterization


#### Forest Nature Conservation
*(Naturwaldforschung / Arten- und Biotopschutz)*

- forest structure and dynamic
- biodiversity modelling
- coarse woody debris detection
