
### Forest Stand Inventory

Integration of Photo Interpreted and LIDAR Attributes Into a Polygonal Forest Inventory Framework (https://bermane.github.io/ontario-inventory/)

"map Site Index over large areas of forest automatically, depicting forest productivity at a much finer spatial resolution than what is common in operational inventories." [@noordermeerPredictingMappingSite2020]

"an approach to develop Site Index models from ALS data" [@tompalskiModelingSiteIndex2022]

"the degree of transferability depends more on the attribute being modelled or the modeling approach applied, and less on the characteristics of the point cloud data." [@tompalskiDemonstratingTransferabilityForest2019]

"dense Laser scanning-based inventory provided more accurate stand estimates than field-based demonstrations" [@perssonTwophaseForestInventory2022]

"explore the potential of LiDAR and other geospatial information sources to model and predict wood quality based on individual-tree and stand structural metrics." [@vanleeuwenAssessmentStandingWood2011]

"Contemporary inventory data demands are shifting, with an increased focus on accurate attribute estimation via the integration of advanced remote sensing data such as airborne laser scanning (ALS).
a conceptual framework for forestry inventory update, which is also known as the establishment of a ‘living inventory’." [@coopsFrameworkRealtimeForest2023]

"detailed forest information from ALS point clouds is useful to indicate regions not suitable
for forest operations" [@gorgensAutomatedOperationalLogging2020]

"predict the need for commercial thinning using airborne lidar data. This study offers a novel approach for planning commercial thinnings using ALS-based structure metrics in order to most effectively utilize the information with the highest acquisition cost—the decisions made in situ by forest inventory experts." [@arumaePlanningCommercialThinnings2022]