
### Germany

Geodata collection, administration and publication in Germany is predominantly organized in federal structures by the land surveying and cadaster authorities of the 16 federal states. Although the Working Committee of the surveying authorities of the states of the Federal Republic of Germany (AdV) defines guidelines and standards there is still a variety of different data types in the realm of laser scanning data. For applications on a broader scale beyond state boundaries it is essential to know the data availability. Hence, information on federal ALS was collected from federal mapping agencies' websites and other source such as personal and Email comunication @tbl-als-federal lists some of the attributes by state, further information is available [here](https://gist.github.com/wiesehahn/6b6c215c227341f4faab03ff96fa7f1b). 

| Federal State | Cost (min)[^1] | Cost (max)[^2] | Year (from)[^3] | Year (to)[^4] | Point Density[^5] | Format | CRS (EPSG) |
|---|---|---|---|---|---|---|---|
| Baden-Württemberg | 10 | 80 | 2016 | 2021 | 8 | LAZ 1.2 | 25832 |
| Bavaria | 0 | 0 | 2011 | 2021 | 1-4 | LAZ 1.2 | 25832 |
| Berlin | 0 | 0 | 2021 | 2021 | 10 | LAS 1.4 | 25833 |
| Brandenburg | 0 | 0 | 2017 | 2022 | 5 | LAZ 1.4 | 25833 |
| Bremen | 80 | 80 | 2017 | 2017 | ? | ? | 25832 |
| Hamburg | ? | ? | 2020 | 2020 | ? | ? | 25832 |
| Hesse | 0 | 0 | 2009 | 2020 | 4 | LAS 1.3 | 25832 |
| Mecklenburg-Western Pomerania | 10 | 80 | 2012 | 2022 | 2-5 | LAZ 1.2 | 25833 |
| Lower Saxony | 3,75 | 30 | 2015 | 2021 | 4 | LAZ 1.2 | 25832 |
| North Rhine-Westphalia | 0 | 0 | 2018 | 2022 | 4-10 | LAZ 1.2 | 25832 |
| Rhineland-Palatinate | 25 | 100 | 2014 | 2022 | 4 | LAZ 1.2 | 25832 |
| Saarland | 120 | 120 | 2016 | 2016 | 4 | LAS 1.2 | 25832 |
| Saxony | 0 | 0 | 2015 | 2022 | 4 | LAZ 1.2 | 25833 |
| Saxony-Anhalt | ? | 80 | 2009 | 2022 | 3-5 | XYZ | 25832 |
| Schleswig-Holstein | ? | ? | ? | ? | 3-5 | ? | 25832 |
| Thuringia | 0 | 0 | 2017 | 2022 | 4 | LAZ 1.4 | 25832 |

: Comparison of available ALS data in Germany by state {#tbl-als-federal}

[^1]: in € per km² (with volume discount; plus processing fee)
[^2]: in € per km² (plus processing fee)
[^3]: oldest data for statewide coverage
[^4]: newsest data for statewide coverage
[^5]: specified minimum number of points per m²


According to @virtanenNationwidePointCloud2017 "topographic databases maintained by national mapping agencies are currently the most common nationwide data sets in geo-information", however this is not true for Germany. Until now there is no single data set which is available for entire Germany. However, there are plans to generate such data. The project [Digital Twin Germany](https://www.business-geomatics.com/2022/11/17/zwillinge-gross-gedacht/) aims to acquire high density point cloud data for Germany. The project is run by the Federal Agency for Cartography and Geodesy (BKG), Germany's national mapping agency. Data acquisition starts in 2023 and the goal is to have a data set for entire Germany by 2024. It is also planned to have at least one repition some years later (2025/26 ?). 
Until now there is only sparse information about details of the project, but most likely the data will be mapped by Geiger-Mode or Single Photon Sensor (Leica SPL100) in the vegegtation period [@hopfstockAufWegDigitalen2021]. It is not planned to make the data available as open source in general, although DTM and DSM mitght be public at 1 meter resolution. Point cloud data  might be accessible for scientific research and national authorities only. However, there is also rumors, that at least a downsampled version of point cloud data will be available. 
