### Individual Tree Segmentation 

Individual Tree Segmentation (ITS) is a technique that automatically delineates individual tree crowns, facilitating accurate tree attribute estimation and forest inventory analysis. Precise Canopy Height Models based on ALS data are the foundation for most methods.

> This study compared the accuracy of four representative individual tree segmentation (ITS) algorithms against benchmark data sets in temperate and tropical forests. We found that all four ITS algorithms were able to segment canopy trees accurately but performed poorly for the understory trees [@caoTreeSegmentationAirborne2022]

> propose a framework for individual tree crown (ITC) segmentation from laser data that focuses on both overstory and understory trees. 
achieve ITC segmentation for forests with various structural attributes. The results also illustrate the potential of using ALS data to delineate low vegetation." [@huoLowVegetationIdentification2022]

> two instance segmentation methods, Mask R–CNN and DETR, were applied to precisely delineate single tree crowns using multispectral images and images generated from UAV lidar data. [@derschCompleteTreeCrown2023]

> compared the performance of four widely used tree segmentation algorithms. 
All algorithms performed reasonably well on the canopy trees. However, all algorithms failed to accurately segment the understory trees. [@caoBenchmarkingAirborneLaser2023]

> present a novel ITC segmentation approach based on the YOLOv5 CNN. [@strakerInstanceSegmentationIndividual2023]